#!/bin/bash


# Will start three elevators on three different simulators

# Start three simulators
gnome-terminal --geometry=80x20+1000+0 -e './SimElevatorServer --port=15541'
gnome-terminal --geometry=80x20+1000+500 -e './SimElevatorServer --port=15542'
gnome-terminal --geometry=80x20+1000+760 -e './SimElevatorServer --port=15543'

# Start three nodes
gnome-terminal --geometry=100x25+50+0 -e 'go run main.go -id=0 -port=15541'
gnome-terminal --geometry=100x25+50+500 -e 'go run main.go -id=1 -port=15542'
gnome-terminal --geometry=80x20+250+760 -e 'go run main.go -id=2 -port=15543'
